### PR TITLE
added more explanations for navigation contexts

### PR DESCRIPTION
**Pull request by danrot**

### CODE REVIEW

**Comment by wachterjohannes** [comment]
ACK maybe you want to add a link to the blog entry?

**Comment by danrot** [comment]
@wachterjohannes I am not sure if we should link from the documentation to the blog, since the blog could be outdated, and the documentation links to an invalid example.

**Comment by wachterjohannes** [comment]
hmm your right (:

**Comment by wachterjohannes** [comment]
could you rebase this PR?

**Comment by danrot** [comment]
@wachterjohannes done

**Pull request merged**
