### PR TITLE
Extracting the find logic from the content migrations

### PR DESCRIPTION
**Pull request by mamazu**
| Q | A
| --- | ---
| Fixed tickets | -
| Related PRs | -
| License | MIT

#### What's in this PR?
This PR separates out a function that is used to find the rows that need to be migrated from the actual migration part.

#### Why?
* The code is cleaner since the removed duplication makes it easier to change which pages should be migrated.
* If people create new migrations they don't need to copy so much boiler plate code

### CODE REVIEW

**Comment by mamazu** [comment]
@alexander-schranz, can someone review this?

**Review by alexander-schranz — APPROVED** [review]
Looks fine from my side can you rebase this for 2.3?

**Comment by mamazu** [comment]
Done

**Comment by alexander-schranz** [comment]
Looks like there was something went wrong in the rebase can you make a `git rebase -i origin/2.3` and remove the commits which are not yours?

**Comment by alexander-schranz** [comment]
ohh sorry the branch target was not changed. did update it :D

**Comment by alexander-schranz** [comment]
@mamazu Thank you!

**Pull request merged**
