### PR TITLE
Add docker configuration for gd library

### PR DESCRIPTION
**Pull request by Amoifr**
| Q | A
| --- | ---
| License | MIT

#### What's in this PR?

Add docker configuration for gd library

#### Why?

Because it wasn"t present when I need ;-)

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@Amoifr Thx for working on this. Can you please rebase your merge request to `2.5` version.

**Comment by Amoifr** [comment]
I've rebased my branch

**Comment by alexander-schranz** [comment]
In the rebase to 2.5 you need to drop the commits which are not yours:

```
git rebase --interactive origin/2.6 --onto origin/2.5
```

Should handle that if there still commits which are drop them and then do a force push to your branch:

```
git push <yourremote> --force
```

**Comment by Amoifr** [comment]
I do the rebase but I still have some changes not of my production

**Comment by Amoifr** [comment]
I do the rebase but I still have some changes not of my production

**Comment by alexander-schranz** [comment]
@Amoifr Thx did the rebase. On 2.6 branch we support Avif if you want to update that docs also with a pull request it would be awesome.

**Pull request merged**
