### PR TITLE
Document the ghost_script configuration for pdf preview

### PR DESCRIPTION
**Pull request by ampaze**
| Q | A
| --- | ---
| Related issue | sulu/sulu#6376
| License | MIT

#### What's in this PR?

Document the ghost_script configuration for pdf preview

#### Why?

It is not documented 😉

### CODE REVIEW

**Comment by ampaze** [comment]
Docs seem to be pretty low on the radar 🤔

**Comment by alexander-schranz** [comment]
Sorry we had some weeks of and had at the end of the year to finish some other things. We are now back to review community pull requests.

**Review by alexander-schranz — CHANGES_REQUESTED** [review]
@ampaze Thx for the pull request. Can you rebase pull request to the `2.3` branch and change the target branch here. As 2.3 is currently the lowest supported sulu 2 version.

**Comment by alexander-schranz** [comment]
@ampaze Thank you!

**Pull request merged**
