### PR TITLE
Updating instructions for Flysystem 3

### PR DESCRIPTION
**Pull request by mamazu**
| Q | A
| --- | ---
| Fixed tickets | -
| Related PRs | https://github.com/sulu/sulu/pull/7687
| License | MIT

#### What's in this PR?
Explain how flysystem integrates into Sulu 3

#### Why?

The setup process for s3 and flysystem has been simplified.

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]

**Comment by alexander-schranz** [comment]
@mamazu can you rebase?

**Comment by mamazu** [comment]
@alexander-schranz This is currently set to merge into 2.x because there is no 3.x branch. Is that fine?

**Comment by alexander-schranz** [comment]
Yes is fine, branch will be renamed when we update the configs in the read the docs UI.

**Comment by mamazu** [comment]
Rebased.

**Pull request merged**
