### PR TITLE
Fix analytics template path

### PR DESCRIPTION
**Pull request by fnagel**
See https://github.com/sulu/sulu/discussions/7692

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Thank you can we use the more modern syntax with `/` instead of `:` and can you rebase and target the 2.5 branch?

**Comment by fnagel** [comment]
Changed the code, but unsure if I did right with the branch as there is that "This branch is out-of-date with the base branch" note form Github.

**Comment by fnagel** [comment]
Maybe I need to close this one and create a new one like this: https://github.com/sulu/sulu-docs/compare/2.5...fnagel:sulu-docs:patch-1?expand=1

**Comment by alexander-schranz** [comment]
@fnagel looks good. Thank you!

**Review by alexander-schranz — APPROVED** [review]

**Pull request merged**
